version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
    groups:
      devDependencies:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "webpack*"
          - "ts-loader"
          - "typescript"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github_actions
