# Contains modifications to the following workflow
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: OpenBlink Extension CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v2
      
    - name: Install Visual Studio C++ Desktop Development
      uses: microsoft/setup-msbuild@v2
      with:
        components: Microsoft.VisualStudio.Component.VC.Tools.x86.x64
        workload: Microsoft.VisualStudio.Workload.VCTools
        includeRecommended: true
        includeOptional: true
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm ci
    - run: npm install -g vsce
    - run: npm run vscode:prepublish
    # - run: vsce package

    - name: Publish to Open VSX Registry
      uses: HaaLeo/publish-vscode-extension@v2
      with:
        pat: ${{ secrets.OPEN_VSX_PAT }}

    - name: Publish to Visual Studio Marketplace
      uses: HaaLeo/publish-vscode-extension@v2
      with:
        pat: ${{ secrets.AZURE_PAT }}
        registryUrl: https://marketplace.visualstudio.com

    - name: End of workflow
      run: echo "End of workflow" 

  
