# Contains modifications to the following workflow
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: OpenBlink Extension CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      # - name: Install Visual Studio Build Tools
      #   if: matrix.os == 'windows-latest'
      #   uses: microsoft/setup-msbuild@v2

      # - name: Install Visual Studio C++ Desktop Development
      #   if: matrix.os == 'windows-latest'
      #   uses: microsoft/setup-msbuild@v2

      # with:
      #   components: Microsoft.VisualStudio.Component.VC.Tools.x86.x64
      #   workload: Microsoft.VisualStudio.Workload.VCTools
      #   includeRecommended: true
      #   includeOptional: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm install --global --production windows-build-tools

      - name: Identify OS
        if: matrix.os == 'macos-latest'
        run: node package_mod.js

      - run: npm install
      - run: npm install -g vsce
      - run: npm run vscode:prepublish
      # - run: vsce package

      - name: Publish to Open VSX Registry(win)
        if: matrix.os == 'windows-latest'
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_PAT }}

      - name: Publish to Visual Studio Marketplace(win)
        if: matrix.os == 'windows-latest'
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.AZURE_PAT }}
          registryUrl: https://marketplace.visualstudio.com

      - name: Publish to Open VSX Registry(mac)
        if: matrix.os == 'macos-latest'
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_PAT }}
          registryUrl: https://open-vsx.org

      - name: Publish to Visual Studio Marketplace(mac)
        if: matrix.os == 'macos-latest'
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.AZURE_PAT }}
          registryUrl: https://marketplace.visualstudio.com

      - name: End of workflow
        run: echo "End of workflow"
