# Contains modifications to the following workflow
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: OpenBlink Extension Matrix CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node-version: [18.x]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Build Native Modules
      run: npm rebuild --update-binary
      
    - name: Prepare Artifacts
      run: |
        mkdir -p platform-bin
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp node_modules/@abandonware/noble/build/Release/noble.node platform-bin/noble-win32.node
        else
          cp node_modules/@abandonware/noble/build/Release/noble.node platform-bin/noble-darwin.node
        fi
        
    - uses: actions/upload-artifact@v4
      with:
        name: noble-binaries
        path: platform-bin/

  package:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        name: noble-binaries
        path: binaries
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Merge Binaries
      run: |
        mkdir -p node_modules/@abandonware/noble/build/Release
        cp binaries/platform-bin/noble-win32.node node_modules/@abandonware/noble/build/Release/
        cp binaries/platform-bin/noble-darwin.node node_modules/@abandonware/noble/build/Release/
        
    - name: Patch Loader
      run: |
        sed -i "s@require('\\./build/Release/noble\\.node')@require(process.platform === 'win32' ? '\\./build/Release/noble-win32.node' : '\\./build/Release/noble-darwin.node')@" node_modules/@abandonware/noble/lib/noble.js
        
    - name: Install VSCE
      run: npm install -g vsce
      
    - name: Prepare for Publishing
      run: npm run vscode:prepublish
      
    - name: Package Extension
      run: vsce package
      
    - name: Publish to Open VSX Registry
      uses: HaaLeo/publish-vscode-extension@v2
      with:
        pat: ${{ secrets.OPEN_VSX_PAT }}
        
    - name: Publish to Visual Studio Marketplace
      uses: HaaLeo/publish-vscode-extension@v2
      with:
        pat: ${{ secrets.AZURE_PAT }}
        registryUrl: https://marketplace.visualstudio.com

    # おわり
    - name: End of workflow
      run: echo "End of workflow" 

  
